name: Generate Snake Animation

on:
  schedule: # executa a cada 12 horas
    - cron: "0 */12 * * *"

  workflow_dispatch:  # permite rodar manualmente
  push:
    branches:
      - main  # troque para "master" se sua branch principal for master

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Gerar snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: lucasnavis
          outputs: dist/snake.svg?palette=github-dark

      - name: Enviar snake.svg para a branch de output
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
